version: '3'
services:
    dns:
      build: ./dns
      ports:
        - '53:53/udp'
    web:
      image: 'nginx:1.19.1-alpine'
      volumes: 
        - './web/html:/usr/share/nginx/html'
      ports:
        - '8080:80'
    proxy:
      image: 'nginx:1.19.1-alpine'
      volumes:
        - './proxy/nginx.conf:/etc/nginx/nginx.conf'
        - './proxy/certs/proxy-ssl.key:/usr/share/nginx/proxy-ssl.key'
        - './proxy/certs/proxy-ssl.crt:/usr/share/nginx/proxy-ssl.crt'
      ports:
        - '80:80'
        - '443:443'
